// <auto-generated />
using System;
using System.Text.Json;
using JobMatch.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobMatch.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JobMatchDbContext))]
    [Migration("20260921115804_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobMatch.Domain.CandidateProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_candidate_profile");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_candidate_profile_user_id");

                    b.ToTable("candidate_profile", (string)null);
                });

            modelBuilder.Entity("JobMatch.Domain.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_company");

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("JobMatch.Domain.CompanyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MemberRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("member_role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_company_member");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasDatabaseName("ux_company_member_company_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_company_member_user_id");

                    b.ToTable("company_member", null, t =>
                        {
                            t.HasCheckConstraint("ck_company_member_role", "member_role IN ('Owner')");
                        });
                });

            modelBuilder.Entity("JobMatch.Domain.CreditAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Balance")
                        .HasColumnType("integer")
                        .HasColumnName("balance");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_profile_id");

                    b.Property<int>("DailyLimit")
                        .HasColumnType("integer")
                        .HasColumnName("daily_limit");

                    b.Property<DateOnly>("PeriodDate")
                        .HasColumnType("date")
                        .HasColumnName("period_date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_credit_account");

                    b.HasIndex("CandidateProfileId")
                        .IsUnique()
                        .HasDatabaseName("ux_credit_account_candidate_profile_id");

                    b.ToTable("credit_account", null, t =>
                        {
                            t.HasCheckConstraint("ck_credit_account_balance", "daily_limit > 0 AND balance >= 0 AND balance <= daily_limit");
                        });
                });

            modelBuilder.Entity("JobMatch.Domain.CreditTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreditAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("credit_account_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_credit_transaction");

                    b.HasIndex("ApplicationId")
                        .IsUnique()
                        .HasDatabaseName("ux_credit_transaction_debit_application_id")
                        .HasFilter("application_id IS NOT NULL AND type = 'Debit'");

                    b.HasIndex("CreditAccountId")
                        .HasDatabaseName("ix_credit_transaction_credit_account_id");

                    b.ToTable("credit_transaction", null, t =>
                        {
                            t.HasCheckConstraint("ck_credit_transaction_amount", "amount > 0");

                            t.HasCheckConstraint("ck_credit_transaction_application", "(type = 'Debit' AND application_id IS NOT NULL) OR (type = 'DailyReset' AND application_id IS NULL)");

                            t.HasCheckConstraint("ck_credit_transaction_type", "type IN ('DailyReset', 'Debit')");
                        });
                });

            modelBuilder.Entity("JobMatch.Domain.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Degree")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("degree");

                    b.Property<short?>("GraduationYear")
                        .HasColumnType("smallint")
                        .HasColumnName("graduation_year");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("institution");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid")
                        .HasColumnName("resume_id");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("specialty");

                    b.HasKey("Id")
                        .HasName("pk_education");

                    b.HasIndex("ResumeId")
                        .HasDatabaseName("ix_education_resume_id");

                    b.ToTable("education", null, t =>
                        {
                            t.HasCheckConstraint("ck_education_graduation_year", "graduation_year IS NULL OR graduation_year BETWEEN 1900 AND 2100");
                        });
                });

            modelBuilder.Entity("JobMatch.Domain.JobApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_profile_id");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("text")
                        .HasColumnName("cover_letter");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid")
                        .HasColumnName("resume_id");

                    b.Property<JsonDocument>("ResumeSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resume_snapshot");

                    b.Property<int>("SnapshotVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("snapshot_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uuid")
                        .HasColumnName("vacancy_id");

                    b.HasKey("Id")
                        .HasName("pk_application");

                    b.HasIndex("ResumeId")
                        .HasDatabaseName("ix_application_resume_id");

                    b.HasIndex("VacancyId")
                        .HasDatabaseName("ix_application_vacancy_id");

                    b.HasIndex("CandidateProfileId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_application_candidate_idempotency");

                    b.HasIndex("CandidateProfileId", "VacancyId")
                        .IsUnique()
                        .HasDatabaseName("ux_application_candidate_vacancy");

                    b.ToTable("application", null, t =>
                        {
                            t.HasCheckConstraint("ck_application_snapshot_version", "snapshot_version > 0");

                            t.HasCheckConstraint("ck_application_status", "status IN ('Submitted', 'Viewed', 'Invited', 'Rejected', 'Withdrawn')");
                        });
                });

            modelBuilder.Entity("JobMatch.Domain.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_profile_id");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DesiredPosition")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("desired_position");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_resume");

                    b.HasIndex("CandidateProfileId")
                        .IsUnique()
                        .HasDatabaseName("ux_resume_candidate_profile_id");

                    b.ToTable("resume", (string)null);
                });

            modelBuilder.Entity("JobMatch.Domain.ResumeSkill", b =>
                {
                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid")
                        .HasColumnName("resume_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.HasKey("ResumeId", "SkillId")
                        .HasName("pk_resume_skill");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_resume_skill_skill_id");

                    b.ToTable("resume_skill", (string)null);
                });

            modelBuilder.Entity("JobMatch.Domain.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_skill");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_skill_name");

                    b.ToTable("skill", (string)null);
                });

            modelBuilder.Entity("JobMatch.Domain.Vacancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requirements");

                    b.Property<int?>("SalaryFrom")
                        .HasColumnType("integer")
                        .HasColumnName("salary_from");

                    b.Property<int?>("SalaryTo")
                        .HasColumnType("integer")
                        .HasColumnName("salary_to");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("work_format");

                    b.HasKey("Id")
                        .HasName("pk_vacancy");

                    b.HasIndex("City")
                        .HasDatabaseName("ix_vacancy_city");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_vacancy_company_id");

                    b.HasIndex("WorkFormat")
                        .HasDatabaseName("ix_vacancy_work_format");

                    b.HasIndex("Status", "PublishedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_vacancy_status_published_at");

                    b.ToTable("vacancy", null, t =>
                        {
                            t.HasCheckConstraint("ck_vacancy_salary", "(salary_from IS NULL OR salary_from >= 0) AND (salary_to IS NULL OR salary_to >= 0) AND (salary_from IS NULL OR salary_to IS NULL OR salary_from <= salary_to)");

                            t.HasCheckConstraint("ck_vacancy_status", "status IN ('Draft', 'Published', 'Closed')");

                            t.HasCheckConstraint("ck_vacancy_work_format", "work_format IN ('Office', 'Remote', 'Hybrid')");
                        });
                });

            modelBuilder.Entity("JobMatch.Domain.VacancySkill", b =>
                {
                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uuid")
                        .HasColumnName("vacancy_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.HasKey("VacancyId", "SkillId")
                        .HasName("pk_vacancy_skill");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_vacancy_skill_skill_id");

                    b.ToTable("vacancy_skill", (string)null);
                });

            modelBuilder.Entity("JobMatch.Domain.WorkExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndedOn")
                        .HasColumnType("date")
                        .HasColumnName("ended_on");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("position");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid")
                        .HasColumnName("resume_id");

                    b.Property<DateOnly>("StartedOn")
                        .HasColumnType("date")
                        .HasColumnName("started_on");

                    b.HasKey("Id")
                        .HasName("pk_work_experience");

                    b.HasIndex("ResumeId")
                        .HasDatabaseName("ix_work_experience_resume_id");

                    b.ToTable("work_experience", null, t =>
                        {
                            t.HasCheckConstraint("ck_work_experience_dates", "ended_on IS NULL OR ended_on >= started_on");
                        });
                });

            modelBuilder.Entity("JobMatch.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("ix_users_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_user_name");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_role", "role IN ('Candidate', 'Employer')");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claim_user_id");

                    b.ToTable("user_claim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_login_user_id");

                    b.ToTable("user_login", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_token", (string)null);
                });

            modelBuilder.Entity("JobMatch.Domain.CandidateProfile", b =>
                {
                    b.HasOne("JobMatch.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("JobMatch.Domain.CandidateProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_profile_users");
                });

            modelBuilder.Entity("JobMatch.Domain.CompanyMember", b =>
                {
                    b.HasOne("JobMatch.Domain.Company", "Company")
                        .WithOne("Member")
                        .HasForeignKey("JobMatch.Domain.CompanyMember", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_company_member_company");

                    b.HasOne("JobMatch.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("JobMatch.Domain.CompanyMember", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_company_member_users");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("JobMatch.Domain.CreditAccount", b =>
                {
                    b.HasOne("JobMatch.Domain.CandidateProfile", "CandidateProfile")
                        .WithOne("CreditAccount")
                        .HasForeignKey("JobMatch.Domain.CreditAccount", "CandidateProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_credit_account_candidate_profile");

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("JobMatch.Domain.CreditTransaction", b =>
                {
                    b.HasOne("JobMatch.Domain.JobApplication", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_credit_transaction_application");

                    b.HasOne("JobMatch.Domain.CreditAccount", "CreditAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("CreditAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_credit_transaction_credit_account");

                    b.Navigation("Application");

                    b.Navigation("CreditAccount");
                });

            modelBuilder.Entity("JobMatch.Domain.Education", b =>
                {
                    b.HasOne("JobMatch.Domain.Resume", "Resume")
                        .WithMany("Educations")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_education_resume");

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("JobMatch.Domain.JobApplication", b =>
                {
                    b.HasOne("JobMatch.Domain.CandidateProfile", "CandidateProfile")
                        .WithMany("Applications")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_application_candidate_profile");

                    b.HasOne("JobMatch.Domain.Resume", "Resume")
                        .WithMany("Applications")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_application_resume");

                    b.HasOne("JobMatch.Domain.Vacancy", "Vacancy")
                        .WithMany("Applications")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_application_vacancy");

                    b.Navigation("CandidateProfile");

                    b.Navigation("Resume");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("JobMatch.Domain.Resume", b =>
                {
                    b.HasOne("JobMatch.Domain.CandidateProfile", "CandidateProfile")
                        .WithOne("Resume")
                        .HasForeignKey("JobMatch.Domain.Resume", "CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resume_candidate_profile");

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("JobMatch.Domain.ResumeSkill", b =>
                {
                    b.HasOne("JobMatch.Domain.Resume", "Resume")
                        .WithMany("ResumeSkills")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resume_skill_resume");

                    b.HasOne("JobMatch.Domain.Skill", "Skill")
                        .WithMany("ResumeSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resume_skill_skill");

                    b.Navigation("Resume");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("JobMatch.Domain.Vacancy", b =>
                {
                    b.HasOne("JobMatch.Domain.Company", "Company")
                        .WithMany("Vacancies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vacancy_company");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("JobMatch.Domain.VacancySkill", b =>
                {
                    b.HasOne("JobMatch.Domain.Skill", "Skill")
                        .WithMany("VacancySkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vacancy_skill_skill");

                    b.HasOne("JobMatch.Domain.Vacancy", "Vacancy")
                        .WithMany("VacancySkills")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vacancy_skill_vacancy");

                    b.Navigation("Skill");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("JobMatch.Domain.WorkExperience", b =>
                {
                    b.HasOne("JobMatch.Domain.Resume", "Resume")
                        .WithMany("WorkExperiences")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_experience_resume");

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("JobMatch.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("JobMatch.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("JobMatch.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobMatch.Domain.CandidateProfile", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("CreditAccount");

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("JobMatch.Domain.Company", b =>
                {
                    b.Navigation("Member");

                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("JobMatch.Domain.CreditAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("JobMatch.Domain.Resume", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Educations");

                    b.Navigation("ResumeSkills");

                    b.Navigation("WorkExperiences");
                });

            modelBuilder.Entity("JobMatch.Domain.Skill", b =>
                {
                    b.Navigation("ResumeSkills");

                    b.Navigation("VacancySkills");
                });

            modelBuilder.Entity("JobMatch.Domain.Vacancy", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("VacancySkills");
                });
#pragma warning restore 612, 618
        }
    }
}
